### ISSUE TITLE
How do I import org.jetbrains.skija?

### ISSUE THREAD

**Issue by rgkirch** [HumbleUI/HumbleUI#2]
Sorry, I'm having trouble getting started. I was looking at the clojure examples in the skija project and tried adding `... (:import [org.jetbrains.skija BackendRenderTarget ...` but I get `java.lang.ClassNotFoundException: org.jetbrains.skija.BackendRenderTarget`. I added `common.fetch_maven("org.jetbrains.skija", "skija-windows", "0.93.4"),` to the run.py file.
How do I import skija?
Thanks!

**Comment by rgkirch** [comment]
Initially I tried `... (:require [io.github.humbleui.skija-windows :as skj]) ...` but that just gives me `java.io.FileNotFoundException: Could not locate io/github/humbleui/skija_windows__init.class, io/github/humbleui/skija_windows.clj or io/github/humbleui/skija_windows.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.`

Ditto with `... (:require [io.github.humbleui.skija :as skj]) ...`.

**Comment by tonsky** [comment]
I am sorry for the confusion! Both Skija and JWM have moved from JetBrains organization to this one, and Maven coordinates changed from JetBrains repo to Maven Central, which I hope is more convenient for the future.

The way it’s setup right now is: Skija after version 0.96.0 lives at `io.github.humbleui.skija:skija-<platform>` and the package name is `io.github.humbleui.skija`.

Versions before 0.96.0 continue to live under `org.jetbrains.skija:skija-<platform>`, but to use them, make sure to specify the JetBrains repo as well (`https://packages.jetbrains.team/maven/p/skija/maven`). I don’t recommend this because only HumbleUI version will continue to be updated/supported.

I did my best to update all the examples, but I might very well missed something — let me know!

Also let me know if you need further assistance, or have any questions. I hope you’ll get Skija running in no time!

**Comment by rgkirch** [comment]
Thanks!
I was looking at [snake/main.clj](https://github.com/JetBrains/skija/blob/master/examples/clojure-snake/src/snake/main.clj) which refers to `org.jetbrains.skija` but that's probably correct since the [build.py](https://github.com/JetBrains/skija/blob/master/script/build.py#L62) for that project also references `org.jetbrains.skija`.
The [deps.edn](https://github.com/JetBrains/skija/blob/master/examples/clojure-snake/deps.edn) file didn't give me any hints. It's just referring to the project's build output.
